name: CI/CD
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: copy via ssh
        uses: appleboy/scp-action@master
        with:
          host: 157.245.154.191
          username: root
          password: o3#2f#ywWwfEFv
          post: 22
          source: .,!node_modules
          target: ~/app
      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: 157.245.154.191
          username: root
          password: o3#2f#ywWwfEFv
          post: 2
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd ~/app
            npm install
            pm2 stop all
            pm2 start src/index.js
